stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: comtols/sensora-frontend-api:latest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - docker logout

deploy:
  stage: deploy
  image: alpine
  script:
    - echo "Deployment logic here (z. B. Container neustarten)"
  only:
    - main
