services:
  mailservice:
    build: ./mailservice
    container_name: mailservice
    ports:
      - "8000:8000"
    env_file:
      - .env

  databasewriter:
    build: ./databasewriter
    container_name: databasewriter
    env_file:
      - .env


  setpointapi:
    build: ./setpointapi
    container_name: setpointapi
    ports:
      - "5000:5000"
    env_file:
      - .env


  solace:
    image: solace/solace-pubsub-standard:latest
    container_name: solace
    ports:
      - "55555:55555"
      - "8080:8080"
      - "8008:8008"
      - "1883:1883"
      - "5672:5672"
      - "9000:9000"
      - "2222:22"
    environment:
      - username_admin_globalaccesslevel=${SOLACE_ADMIN_USER}
      - username_admin_password=${SOLACE_ADMIN_PASS}
      - system_scaling_maxconnectioncount=100
      - system_scaling_maxqueuemessagecount=100
      - system_scaling_maxqueuesize=100M
      - system_scaling_maxqueuesize_guaranteed=100M
    volumes:
      - solace-data:/var/lib/solace
      - solace-config:/var/lib/solace/config
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    shm_size: 4g
    mem_limit: 4g
    mem_reservation: 2g

  solace-init:
    build: ./solace-init
    environment:
      - SOLACE_USER=${SOLACE_ADMIN_USER}
      - SOLACE_PASS=${SOLACE_ADMIN_PASS}
      - SOLACE_HOST=http://solace:8080


  auth-service:
    build: ./auth-service
    container_name: auth-service
    volumes:
      - ./config:/config
    ports:
      - "5001:5000"
    environment:
      - SOLACE_HOST=http://solace:8080
      - SOLACE_VPN=default
      - SOLACE_ADMIN_USER=${SOLACE_ADMIN_USER}
      - SOLACE_ADMIN_PASS=${SOLACE_ADMIN_PASS}
      - ADMIN_KEY=${ADMIN_KEY}

volumes:
  solace-data:
  solace-config:
