services:
  frontend:
    build:
      context: ../sensora-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sensora
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"



