services:
  #frontend:
  #  build:
  #    context: ../frontend
  #    dockerfile: Dockerfile
  #  ports:
  #    - "80:80"
  #  depends_on:
  #    - db

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        GIT_TOKEN: ${GIT_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sensora
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
